### PR TITLE
Feature/coastal app

### PR DESCRIPTION
**Pull request by platipodium**
I reviewed your code changes.  Thank you!  Everything seems straightforward.  Thank you, in particular, for keeping to the coding style.  I think this is ready to be merged.

### CODE REVIEW

**Comment by josephzhang8** [comment]
Thx Ufuk, Carsten!
@platipodium: please go ahead and merge. Thx.

**Comment by josephzhang8** [comment]
@platipodium : I review the new code from Ufuk and it looks fine to me. Plz review and if u r OK, go ahead and approve and merge. Thx.

**Comment by josephzhang8** [comment]
@platipodium : I take that back; it seems the PR is in progress and cannot be merged.

**Comment by platipodium** [comment]
Has been reviews by Joseph and myself and approved.

**Pull request merged**
